#
# (C) Copyright 2018:
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# SPDX-License-Identifier:	GPL-2.0+
#

# BIFSD DEV
obj-$(CONFIG_X2_BIFSD_DEV)		+= x2_bifsd.o
obj-$(CONFIG_X2_BIFSD_DEV)		+= notify.o
