obj-$(CONFIG_BPU)		+= bpu_framework.o
bpu_framework-objs		:=  bpu_drv.o bpu_ctrl.o \
							bpu_debug.o bpu_prio.o \
							bpu_sched.o bpu_stat.o
obj-$(CONFIG_BPU_ONDEMAND_GOVERNOR) += bpu_governor.o

