#
# Makefile for the Linux Kernel IPS specific device drivers.
#
obj-y += ipu_hw_reg.o 
obj-y += x2a_dev_ipu.o 
		
EXTRA_CFLAGS += -Idrivers/media/platform/hobot/vio/
EXTRA_CFLAGS += -Idrivers/media/platform/hobot/vio/ips/
