#
# Makefile for the Linux Kernel IPS specific device drivers.
#
obj-y += ipu_dev.o
obj-y += ipu_drv.o
obj-y += ipu_slot.o
obj-y += ipu_slot_dual.o
obj-y += ipu_single.o
obj-y += ipu_dual.o
obj-y += ipu_feed_back.o
