clean:
	${MAKE} -C pdu clean
	${MAKE} -C core clean
	${MAKE} -C re clean
	${MAKE} -C trng clean
	${MAKE} -C pka clean
	${MAKE} -C mpm clean
	${MAKE} -C ea clean
	${MAKE} -C saspa clean
	${MAKE} -C eape clean
	${MAKE} -C clp30 clean
	${MAKE} -C test/offload clean
	${MAKE} -C xfrm clean

