#
# Makefile for the Linux Kernel IPS specific device drivers.
#
obj-$(CONFIG_HOBOT_IAR) += hobot_iar.o
obj-$(CONFIG_HOBOT_IAR) +=	hobot_iar_cdev.o
obj-$(CONFIG_HOBOT_IAR) +=	hobot_iar_mmap.o
obj-$(CONFIG_HOBOT_IAR) += hobot_rotation_neon64.o
obj-$(CONFIG_HOBOT_IAR) += mipi_dsi.o
