

elpspaccdev-objs += spacc_dev.o
obj-$(CONFIG_CRYPTO_DEV_HOBOT_DEV) += elpspaccdev.o

elpspacccrypto-objs += cryptoapi.o cryptoapi-ahash.o cryptoapi-cipher.o cryptoapi-aead.o
obj-$(CONFIG_CRYPTO_DEV_HOBOT_CRYPTO) += elpspacccrypto.o

spaccexample-objs += example.o
obj-$(CONFIG_CRYPTO_DEV_HOBOT_EXAMPLE) += spaccexample.o
