#
# Makefile for HDMI sii9022 chip drivers.

#obj-$(CONFIG_HDMI_Sii902xA)	+= SiIIIC.o
obj-$(CONFIG_HOBOT_HDMI)	+= siHdmiTx_902x_TPI.o
obj-$(CONFIG_HOBOT_HDMI)	+= hdmi_sii902xA.o
#obj-$(CONFIG_HDMI_Sii902xA)	+= hdmi_EDID.o

#ccflags-$(CONFIG_I2C_DEBUG_BUS) := -DDEBUG
