#
# Makefile for HDMI sii9022 chip drivers.

obj-$(CONFIG_HOBOT_HDMI) += hobot_hdmi.o
hobot_hdmi-objs += siHdmiTx_902x_TPI.o
hobot_hdmi-objs += hdmi_sii902xA.o

#obj-$(CONFIG_HDMI_Sii902xA)	+= hdmi_EDID.o

#ccflags-$(CONFIG_I2C_DEBUG_BUS) := -DDEBUG
