#
# Makefile for the Linux Kernel IPS specific device drivers.
#
#obj-$(CONFIG_HOBOT_IAR) += x2_iar.o
#obj-$(CONFIG_HOBOT_IAR) +=	x2_iar_cdev.o
#obj-$(CONFIG_HOBOT_IAR) +=	x2_iar_mmap.o
obj-$(CONFIG_HOBOT_MIPI) += x2_panel_config.o x2_lt9211_config.o x2_lt9211_dev.o
