obj-$(CONFIG_HOBOT_HBIPC_ETH)     += hbipc_eth.o
obj-$(CONFIG_HOBOT_BIF_LITE_CORE) += bif_lite.o bif_platform.o hbipc_lite.o
obj-$(CONFIG_HOBOT_BIF_LITE_SPI)  += bif_dev_spi.o
obj-$(CONFIG_HOBOT_BIF_LITE_SD)   += bif_dev_sd.o
obj-$(CONFIG_HOBOT_BIF_LITE_ETH)  += bif_dev_eth.o
