#
# Makefile for the Linux Kernel IPS specific device drivers.
#
obj-y += ipu_hw_reg.o
obj-y += hobot_dev_ipu.o

EXTRA_CFLAGS += -Idrivers/media/platform/hobot/common_api/
EXTRA_CFLAGS += -Idrivers/media/platform/hobot/ips/
