#
# Makefile for HDMI lt8618sxb chip drivers.

obj-$(CONFIG_HOBOT_HDMI_LT8618) += hobot_hdmi_lt8618.o
hobot_hdmi_lt8618-objs += hobot_lt8618sxb_dev.o
hobot_hdmi_lt8618-objs += hobot_lt8618sxb_config.o

