#
# Makefile for the Linux Kernel IPS specific device drivers.
#
obj-y += gdc_hw_reg.o
obj-y += gdc_dev.o

EXTRA_CFLAGS += -Idrivers/media/platform/hobot/common_api/
EXTRA_CFLAGS += -Idrivers/media/platform/hobot/ips/

