# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the Linux Kernel SOC specific device drivers.
#

obj-$(CONFIG_ARCH_ACTIONS)	+= actions/
obj-$(CONFIG_ARCH_AT91)		+= atmel/
obj-y				+= bcm/
obj-$(CONFIG_ARCH_DOVE)		+= dove/
obj-$(CONFIG_MACH_DOVE)		+= dove/
obj-y				+= fsl/
obj-$(CONFIG_ARCH_MXC)		+= imx/
obj-$(CONFIG_SOC_XWAY)		+= lantiq/
obj-$(CONFIG_ARCH_MEDIATEK)	+= mediatek/
obj-$(CONFIG_ARCH_MESON)	+= amlogic/
obj-$(CONFIG_ARCH_QCOM)		+= qcom/
obj-y				+= renesas/
obj-$(CONFIG_ARCH_ROCKCHIP)	+= rockchip/
obj-$(CONFIG_SOC_SAMSUNG)	+= samsung/
obj-$(CONFIG_ARCH_SUNXI)	+= sunxi/
obj-$(CONFIG_ARCH_TEGRA)	+= tegra/
obj-$(CONFIG_SOC_TI)		+= ti/
obj-$(CONFIG_ARCH_U8500)	+= ux500/
obj-$(CONFIG_PLAT_VERSATILE)	+= versatile/
obj-$(CONFIG_ARCH_ZX)		+= zte/
obj-$(CONFIG_X2_CNN_HOST)	+= hobot/cnn_host/
obj-$(CONFIG_X2_CNN_MM)	+= hobot/cnn_mm/
obj-$(CONFIG_X2_DIAG)	+= hobot/diag/
obj-$(CONFIG_HOBOT_PM)	+= hobot/pm/
obj-$(CONFIG_HOBOT_MCU_IRQ)	+= hobot/mcu_irq/
obj-$(CONFIG_HOBOT_BIF_BASE)	+= hobot/bif_base/
obj-$(CONFIG_HOBOT_BIF_ETHERNET)	+= hobot/bif_ethernet/
obj-$(CONFIG_HOBOT_BIF_SIO)	+= hobot/bif_sio/
obj-$(CONFIG_HOBOT_BIF_LITE_CORE)  += hobot/bif_lite/
obj-$(CONFIG_HOBOT_BIF_LITE_SPI)   += hobot/bif_lite/
obj-$(CONFIG_HOBOT_BIF_LITE_SD)    += hobot/bif_lite/
obj-$(CONFIG_HOBOT_HBIPC_ETH)    += hobot/bif_lite/
obj-y	+= hobot/ddr_monitor/
obj-y	+= hobot/socinfo/
