#
# Makefile for the Linux Kernel IPS specific device drivers.
#
#ifdef CONFIG_X2_IAR
#obj-m += x2_iar.o
#obj-m += x2_iar_cdev.o
#endif

obj-$(CONFIG_X2_IAR) +=	x2_iar.o
obj-$(CONFIG_X2_IAR) +=	x2_iar_cdev.o
