#
# Makefile for the Linux Kernel IPS specific device drivers.
#
obj-$(CONFIG_X2_IAR) += x2_iar.o
obj-$(CONFIG_X2_IAR) +=	x2_iar_cdev.o
obj-$(CONFIG_X2_IAR) +=	x2_iar_mmap.o
obj-$(CONFIG_X2_IAR) += x2_rotation_neon64.o
obj-$(CONFIG_X2_IAR) += mipi_dsi.o
