dtb-$(CONFIG_X2_FPGA) += hobot-x2-fpga.dtb
dtb-$(CONFIG_X2_SOC)  += hobot-x2-soc.dtb
dtb-$(CONFIG_X2_SOC)  += hobot-x2-som.dtb
dtb-$(CONFIG_X2_SOC)  += hobot-x2-dev.dtb
dtb-$(CONFIG_X2_SOC)  += hobot-j2-som.dtb
dtb-$(CONFIG_X2_SOC)  += hobot-x2-som-ipc.dtb
dtb-$(CONFIG_X2_SOC)  += hobot-j2-mono.dtb
dtb-$(CONFIG_X2_SOC)  += hobot-j2-dev.dtb

always		:= $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb
