#
# Makefile for the Linux Kernel IPS specific device drivers.
#
obj-$(CONFIG_HOBOT_IPS_X2) += x2_ips.o
obj-$(CONFIG_HOBOT_IPS_X2) += x2_ips_cdev.o
obj-$(CONFIG_HOBOT_SIF_X2) += sif/
obj-$(CONFIG_HOBOT_IPU_X2) += ipu/
obj-$(CONFIG_HOBOT_ISP_X2) += isp/
