# SPDX-License-Identifier: GPL-2.0
# generic pinmux support

subdir-ccflags-$(CONFIG_DEBUG_PINCTRL)	+= -DDEBUG
obj-$(CONFIG_PINCTRL_HOBOT_X2)	+= pinctrl-x2.o
obj-$(CONFIG_HOBOT_PINCTRL_CDEV) += hb_pinctrl_cdev.o
