#
# Makefile for the Linux Kernel ISP of IPS specific device drivers
# on x2 chip.
#

obj-$(CONFIG_HOBOT_ISP_X2) += isp_dev.o
obj-$(CONFIG_HOBOT_ISP_X2) += isp_base.o
obj-$(CONFIG_HOBOT_ISP_X2) += isp.o
