#
# Makefile for the Linux Kernel DRR specific device drivers
# on x2 chip.
#

obj-$(CONFIG_HOBOT_DDR_MON) += hobot_ddr_monitor.o hobot_ddr_mpu.o
obj-$(CONFIG_HOBOT_APB_TIMEOUT) += hobot_apb_timeout.o
