# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the Linux Kernel HOBOT SOC specific device drivers.
#

obj-$(CONFIG_HOBOT_CNN_HOST)	+= cnn_host/
obj-$(CONFIG_HOBOT_CNN_MM)		+= cnn_mm/
obj-$(CONFIG_HOBOT_DIAG)		+= diag/
obj-$(CONFIG_HOBOT_PM)		+= pm/
obj-$(CONFIG_HOBOT_MCU_IRQ)	+= mcu_irq/
obj-$(CONFIG_HOBOT_BIFSPI_DEV)		+= bifspi/
obj-$(CONFIG_HOBOT_BIFSD_DEV)		+= bifsd/
obj-$(CONFIG_HOBOT_BIF_BASE)		+= bif_base/
obj-$(CONFIG_HOBOT_BIF_ETHERNET)	+= bif_ethernet/
obj-$(CONFIG_HOBOT_BIF_SIO)		+= bif_sio/
obj-$(CONFIG_HOBOT_BIF_LITE_CORE)  	+= bif_lite/
obj-$(CONFIG_HOBOT_BIF_LITE_SPI)   	+= bif_lite/
obj-$(CONFIG_HOBOT_BIF_LITE_SD)    	+= bif_lite/
obj-$(CONFIG_HOBOT_HBIPC_ETH)    	+= bif_lite/
obj-$(CONFIG_HOBOT_DDR_MON)	+= ddr_monitor/
obj-$(CONFIG_HOBOT_SOCINFO)	+= socinfo/
obj-$(CONFIG_HOBOT_VCAM)	+= vcam/
obj-$(CONFIG_HOBOT_IAR)		+= iar/
obj-$(CONFIG_HOBOT_XJ3_CV_USRDRV)	+= usrdrv/
