ccflags-$(CONFIG_X2_MIPI_CLK_RECALCULATION) += -DADJUST_CLK_RECALCULATION
obj-$(CONFIG_X2_MIPI_HOST) += x2_mipi_host.o
obj-$(CONFIG_X2_MIPI_DEV) += x2_mipi_dev.o
obj-$(CONFIG_X2_MIPI_PHY) += x2_mipi_dphy.o
